"""Generates the rig tables from Tools/content/rig_defs.py.

    python Tools/content/gen_rigs.py

Writes:
    Source/Unreal_Minecraft/Render/MCRigTable.inl   included by MCRig.cpp
    Tools/BlenderMCP/rig_table.py                   pasted into the Blender builder
"""
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)

import rig_defs  # noqa: E402


def f(v):
    """Float literal for C++ (compact, always with a decimal point)."""
    s = ("%.4f" % v).rstrip("0")
    if s.endswith("."):
        s += "0"
    if s in ("-0.0",):
        s = "0.0"
    return s + "f"


def vec(v):
    return "{ %s, %s, %s }" % (f(v[0]), f(v[1]), f(v[2]))


def write_cpp(rigs, path):
    lines = [
        "// Generated by Tools/content/gen_rigs.py from Tools/content/rig_defs.py - do not edit by hand.",
        "// Pivots are relative to the parent part; boxes are relative to the part's own pivot (blocks).",
        "",
        "static const FMCRigPartSpec GRigPartSpecs[] =",
        "{",
    ]
    rig_rows = []
    first = 0
    for r in rigs:
        for p in r.parts:
            lines.append('\t{ TEXT("%s"), %d, EMCRigRole::%s, %s, %s, %s, %d, 0x%06X, %s },' % (
                p.name, p.parent, p.role, vec(p.pivot), vec(p.box_min), vec(p.box_max),
                p.index, p.color, "true" if p.emissive else "false"))
        rig_rows.append('\t{ TEXT("%s"), %s, %d, %d, %d, %s, %d, %d },' % (
            r.name, f(r.scale), r.head, r.right_arm, r.left_arm, vec(r.hand_offset), first, len(r.parts)))
        first += len(r.parts)
    lines += ["};", "", "static const FMCRigSpec GRigSpecs[] =", "{"] + rig_rows + ["};", ""]
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(lines))


def write_blender(rigs, path):
    """Plain literals only: the Blender builder runs under the MCP Safe Mode validator."""
    out = [
        "# Generated by Tools/content/gen_rigs.py from Tools/content/rig_defs.py - do not edit by hand.",
        "# One entry per rig: (name, [(part, parent, role, entity_space_pivot, box_min, box_max, color, emissive)])",
        "# Coordinates are Unreal entity space in blocks; the builder converts to Blender (y -> -y).",
        "RIG_TABLE = [",
    ]
    for r in rigs:
        parts = []
        for i, p in enumerate(r.parts):
            ap = r.absolute_pivot(i)
            parts.append("(%r, %d, %r, (%.4f, %.4f, %.4f), (%.4f, %.4f, %.4f), (%.4f, %.4f, %.4f), 0x%06X, %s)" % (
                p.name, p.parent, p.role, ap[0], ap[1], ap[2],
                p.box_min[0], p.box_min[1], p.box_min[2], p.box_max[0], p.box_max[1], p.box_max[2],
                p.color, "True" if p.emissive else "False"))
        out.append("    (%r, [\n        %s,\n    ])," % (r.name, ",\n        ".join(parts)))
    out.append("]")
    io.open(path, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")


def main():
    rigs = rig_defs.build_all()
    cpp = os.path.join(ROOT, "Source", "Unreal_Minecraft", "Render", "MCRigTable.inl")
    bl = os.path.join(ROOT, "Tools", "BlenderMCP", "rig_table.py")
    write_cpp(rigs, cpp)
    write_blender(rigs, bl)
    print("wrote %d rigs / %d parts" % (len(rigs), sum(len(r.parts) for r in rigs)))
    print("  " + cpp)
    print("  " + bl)


if __name__ == "__main__":
    main()
