class_name BlockDef
extends Resource
## Resource-based definition of a block type. Instances are generated by BlockDB from data tables.

@export var id: int = 0
@export var name: String = ""
@export var display: String = ""
@export var model: int = 1          # BlockDB.M_* model kind
@export var render: int = 0         # BlockDB.R_* render layer
@export var tex: Dictionary = {}    # face key -> texture name ("all","top","bottom","side","front","end", ...)
@export var hardness: float = 1.0   # -1 = unbreakable
@export var resistance: float = 1.0
@export var tool: String = ""       # pickaxe/axe/shovel/hoe/shears/sword
@export var tier: int = 0           # minimum tool tier for drops (1 wood, 2 stone, 3 iron, 4 diamond)
@export var needs_tool: bool = false
@export var drop: String = ""       # "" = itself, "-" = nothing, otherwise item name (or loot key)
@export var drop_count: Vector2i = Vector2i(1, 1)
@export var sound: String = "stone"
@export var light: int = 0
@export var opacity: int = 15
@export var solid: bool = true
@export var full: bool = true       # full opaque cube: culls neighbour faces and casts AO
@export var replaceable: bool = false
@export var tint: int = 0           # BlockDB.T_* biome tint kind
@export var tabs: PackedStringArray = PackedStringArray(["building"])
@export var gravity: bool = false
@export var flammable: bool = false
@export var has_item: bool = true
@export var icon: String = "iso"    # iso / sprite / texture:<name> / item:<name>
@export var tags: PackedStringArray = PackedStringArray()
@export var place: String = ""      # placement rule
@export var interact: String = ""   # right-click behaviour key
@export var tick: String = ""       # random / scheduled tick behaviour key
@export var slip: float = 0.6
@export var speed: float = 1.0
@export var jump: float = 1.0
@export var climb: bool = false
@export var fluid: int = 0          # 1 water, 2 lava
@export var xp: Vector2i = Vector2i.ZERO
@export var silk_only: bool = false # drops only with silk touch (glass, ice...)
@export var cull_same: bool = false # faces between two identical blocks are culled (glass, ice)
@export var waterlogged: bool = false  # always rendered/treated as inside water (kelp, seagrass)
@export var damage: float = 0.0     # contact damage (cactus, magma)
@export var color: Color = Color.WHITE  # map/particle colour
@export var props: Dictionary = {}  # misc extra properties
