class_name ItemDef
extends Resource
## Resource-based item definition (generated by ItemDB from ItemCatalog data and the block registry).

@export var id := 0
@export var name := ""
@export var display := ""
@export var max_stack := 64
@export var kind := "misc"          # block, tool, weapon, armor, food, material, bucket, throwable, spawn_egg, potion...
@export var block := ""             # block placed on use
@export var tool := ""              # pickaxe, axe, shovel, hoe, sword, shears, spear
@export var tier := 0               # harvest tier (1 wood/gold, 2 stone/copper, 3 iron, 4 diamond/netherite)
@export var mine_speed := 1.0
@export var damage := 1.0           # attack damage (hearts x2)
@export var attack_speed := 4.0
@export var reach_bonus := 0.0
@export var durability := 0
@export var armor_slot := -1        # 0 feet, 1 legs, 2 chest, 3 head
@export var armor := 0
@export var toughness := 0.0
@export var knockback_res := 0.0
@export var material := ""          # tier material name (for textures / repair)
@export var food := 0
@export var saturation := 0.0
@export var fuel := 0               # furnace burn ticks
@export var tabs := PackedStringArray()
@export var rarity := 0             # 0 common, 1 uncommon, 2 rare, 3 epic
@export var enchantability := 0
@export var use := ""               # right-click behaviour key
@export var icon := ""              # "block:<name>", "sprite:<name>"
@export var color := Color.WHITE    # tint colour (dyes, potions, eggs)
@export var color2 := Color.WHITE
@export var props := {}


func is_damageable() -> bool:
	return durability > 0


func is_block() -> bool:
	return block != ""
